#! /usr/bin/bash
# This script updates the status bar by setting xsetroot -name

# Variables
# Formatting
left_seperator=""
# Control
tick_rate=60 # Approximately how often should the display be updated
# Battery : These are the icons used by the battery display
battery_full="󱊣"
battery_mid="󱊢"
battery_low="󱊡"
battery_empt="󰂎"
battery_full_chr="󱊦"
battery_mid_chr="󱊥"
battery_low_chr="󱊤"
battery_empt_chr="󰢟"
# Memory
memory_chr=""
#memory_total=$(free -h | grep Mem | awk '{print $2}')

# Info Gathering Functions
function check_date () {
	ret=$(date +"%a %b %_d")
	echo $ret
}

function check_time() {
	ret=$(date +"%-I:%M%P")
	echo $ret
}

function check_battery () {
	percent=$(cat /sys/class/power_supply/BAT0/capacity)
	status=$(cat /sys/class/power_supply/BAT0/status)

	if [ "$status" = "Charging" ]; then
		([[ "$percent" -lt 25 ]] && echo "$battery_empt_chr $percent%") || \
		([[ "$percent" -lt 50 ]] && echo "$battery_low_chr $percent%") || \
		([[ "$percent" -lt 75 ]] && echo "$battery_mid_chr $percent%") || \
		([[ "$percent" -le 100 ]] && echo "$battery_full_chr $percent%")
	else
		([[ "$percent" -lt 25 ]] && echo "$battery_empt $percent%") || \
		([[ "$percent" -lt 50 ]] && echo "$battery_low $percent%") || \
		([[ "$percent" -lt 75 ]] && echo "$battery_mid $percent%") || \
		([[ "$percent" -le 100 ]] && echo "$battery_full $percent%")
	fi
}

function check_ram () {
#	memory_free=$(free -h | grep Mem | awk '{print $3}' | sed 's/[^0-9.]*//g')
#	echo "${memory_chr}  ${memory_free}/${memory_total}"
	mem=$(free | grep Mem | awk '{print $3/$2 * 100.0}')
	echo "${memory_chr} ${mem%.*}%"
}

# Primary Functions
function adjust_timing () { 
	# The command is not launched at exactly 0s and,
	# small innacurracies will compound to make the time display at weird intervals over time. 
	# This ensures that the time is set at the top of the minute
	off_by=$(date +"%-S")
	corrected_tick=$(($tick_rate-off_by))
	echo $corrected_tick
}

function set_status () {
	statusline=$" "
	statusline+=" $left_seperator $(check_ram)"
	statusline+=" $left_seperator $(check_battery)"
	statusline+=" $left_seperator $(check_time) $(check_date)"
	statusline+=" "
	
	xsetroot -name "$statusline"
	#xsetroot -name "[status2d] ^c#FF0000^red text with blue rectangle^c#55cdfc^^r3,3,14,14^^f20^^c#FFFFFF^^b#f7a8b8^ and white text on pink background "
}

 
# Main Loop
while :
do
	set_status
	sleep $(adjust_timing)
done

